### ISSUE TITLE
TypeError: paragraph.pageBreakBefore is not a function

### ISSUE THREAD

**Issue by sergiofm** [dolanmiu/docx#120]
Hi!
I'm trying to use pageBreakBefore() in a paragraph like [this](https://docx.js.org/#/usage/paragraph?id=page-break-before) but I'm getting a error. I'm useing docx v3.6.0.

Here's my code:
```javascript
const paragraph = new docx.Paragraph();
const text = new docx.TextRun(childNode.title);
paragraph.addRun(text);
paragraph.heading1();
paragraph.pageBreakBefore();
doc.addParagraph(paragraph);
```

And here's the error:
```
(node:26371) UnhandledPromiseRejectionWarning: TypeError: paragraph.pageBreakBefore is not a function
    at node.nodeChilds.forEach.childNode (/home/sergio/dev/mettzer/docx-builder/src/render/abnt.js:62:19)
    at Array.forEach (<anonymous>)
    at project.document.documentNodes.forEach.node (/home/sergio/dev/mettzer/docx-builder/src/render/abnt.js:57:23)
    at Array.forEach (<anonymous>)
    at Object.renderProject (/home/sergio/dev/mettzer/docx-builder/src/render/abnt.js:56:36)
    at ProjectUtils.getProject.then.project (/home/sergio/dev/mettzer/docx-builder/index.js:14:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:26371) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without acatch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26371) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dolanmiu** [comment]
This is a feature in the upcoming `4.0.0`!

`paragraph.pageBreakBefore is not a function`

It works on the master branch though

**Comment by sergiofm** [comment]
Ok, thank you!

Is there any prevision of when v4.0.0 will be released?

**Comment by dolanmiu** [comment]
in about one and a half weeks

**Comment by dolanmiu** [comment]
4.0.0 released!
