### ISSUE TITLE
TypeError: Cannot read property 'emus' of undefined when positioning Image

### ISSUE THREAD

**Issue by BenediktMiller** [dolanmiu/docx#173]
Hello,

I am trying to add an Image to my document and then position it, I am using this code snippet (slightly modified copy & paste from the docs)

```
const imageData = doc.createImage(fs.readFileSync('./image.PNG'), 903, 1149);

new docx.PictureRun(imageData, {
    position: docx.PlacementPosition.FLOATING,
    floating: {
        horizontalPosition: {
            relative: docx.HorizontalPositionRelativeFrom.PAGE,
            align: docx.HorizontalPositionAlign.LEFT,
        },
        verticalPosition: {
            relative: docx.VerticalPositionRelativeFrom.PAGE,
            align: docx.VerticalPositionAlign.TOP,
        },
    },
});
```

But I get the following error:
```
node_modules/docx/build/index.js:29280
            relativeHeight: dimensions.emus.y,
                                       ^

TypeError: Cannot read property 'emus' of undefined
    at new Anchor (node_modules/docx/build/index.js:29280:40)
    at new Drawing (node_modules/docx/build/index.js:29212:28)
    at new PictureRun (node_modules/docx/build/index.js:29166:24)
    at Object.<anonymous> (controllers/reporting/reportingController.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

Am I doing something wrong or is the positioning feature broken?

-> I am using version 4.1.0

Best regards,
Benedikt

**Comment by h4buli** [comment]
Hi @BenediktMiller, 

Sorry for the late response. I hope we can still help :-)

As it looks the issue is they way how you create the imageData object.
So if you change it to:
`const imageData = doc.createImageData('My cool image name', fs.readFileSync('./image.PNG'), 903, 1149);`

We use different method to create the image data - we provide all the values like image name (can be different than file name), file data and desired dimensions (can be resized for example).

**Comment by dolanmiu** [comment]
@h4buli I simplified the way images are created, so `const imageData = doc.createImage(fs.readFileSync('./image.PNG'), 903, 1149);` is correct!

**Comment by sleepinzombie** [comment]
@BenediktMiller Did you get a fix for this? I am having this same issue.

**Comment by dolanmiu** [comment]
Can you show me your code? @sleepinzombie

**Comment by sleepinzombie** [comment]
It's almost the same as OP.

```
this.generatedStamp =  doc.createImage(Buffer.from(this.stamp, 'base64'));
    new docx.PictureRun(this.generatedStamp, {
      position: docx.PlacementPosition.FLOATING,
      floating: {
          horizontalPosition: {
              relative: docx.HorizontalPositionRelativeFrom.PAGE,
              align: docx.HorizontalPositionAlign.LEFT,
          },
          verticalPosition: {
              relative: docx.VerticalPositionRelativeFrom.PAGE,
              align: docx.VerticalPositionAlign.TOP,
          },
      },
  });
```

**Comment by dolanmiu** [comment]
Can you try something like this:

https://github.com/dolanmiu/docx/blob/master/demo/demo23.ts

**Comment by efx** [comment]
Seeing the same issue using the following snippet:
```javascript
const logo = await fetch('/assets/some-logo.png'); 
const headerLogo = doc.createImage(logo.blob(), 256, 61);
new docx.PictureRun(headerLogo, {
	position: docx.PlacementPosition.FLOATING,
	floating: {
		horizontalPosition: {
			relative: docx.HorizontalPositionRelativeFrom.PAGE,
			align: docx.HorizontalPositionAlign.RIGHT
		},
		verticalPosition: {
			relative: docx.VerticalPositionRelativeFrom.PAGE,
			align: docx.VerticalPositionAlign.TOP
		}
	}
});
```
I am using this in the browser. This error appears as `imageData` does not have `dimensions` property defined.
<img width="1013" alt="screen shot 2018-11-28 at 12 08 05" src="https://user-images.githubusercontent.com/472721/49168844-684c8a00-f306-11e8-9f0c-ef771703af9a.png">
