### ISSUE TITLE
Failed to create an instance of docx.Numbering()

### ISSUE THREAD

**Issue by denkk0** [dolanmiu/docx#2197]
Basically title says it all. I am trying to create an instance of `docx.Numbering()` following the documentation [here](https://docx.js.org/#/usage/numbering) and it's failing. 

Code: 
```javascript
const numbering = new docx.Numbering();
```

Output:
```
C:\Users\denkk0\Desktop\word-edit\node_modules\docx\build\index.js:2
!function(e,t){"object"==typeof exports&&"object"==type [...]










TypeError: Cannot read properties of undefined (reading 'config')
    at new _o (C:\Users\denkk0\Desktop\word-edit\node_modules\docx\build\index.js:2:294922)
    at Object.<anonymous> (C:\Users\denkk0\Desktop\word-edit\main.js:27:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

I trimmed the output (and replaced with [...]), because it is outputting the whole `node_modules/docx/build/index.js` file.

**Comment by denkk0** [comment]
Closed, relates to: https://github.com/dolanmiu/docx/issues/2081
