### ISSUE TITLE
What I am doing wrong ?

### ISSUE THREAD

**Issue by akshayOren** [dolanmiu/docx#2585]
### Discussed in https://github.com/dolanmiu/docx/discussions/2584

<div type='discussions-op-text'>

<sup>Originally posted by **akshayOren** February  9, 2024</sup>
Doing this 
```javascript
const doc = new docx.Document();
``` 

gives this error.
```javascript
C:\Users\Akshay\Desktop\pdf\pupppdf\node_modules\docx\build\index.cjs:15434
      creator: (_a = options2.creator) != null ? _a : "Un-named",
                              ^

TypeError: Cannot read properties of undefined (reading 'creator')
    at new File (C:\Users\Akshay\Desktop\pdf\pupppdf\node_modules\docx\build\index.cjs:15434:31)
    at Object.<anonymous> (C:\Users\Akshay\Desktop\pdf\pupppdf\index2.js:16:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49
``` </div>

**Comment by DarkTraveler** [comment]
For fix library

`
creator: (options2?.creator != null) ? options2.creator : "Un-named",
`

**Comment by dolanmiu** [comment]
You need to add some options into the document. Take a look at the examples
