### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: doc.addParagraph is not a function

### ISSUE THREAD

**Issue by dil-wainstead** [dolanmiu/docx#383]
I found this bug in 5.0.0-rc5, and also in the master branch as of this morning.

I'm running the first example from https://runkit.com/dolanmiu/docx-demo1 in a new scratch project:

node --version
v10.16.3
npm --version
6.10.3

When I run the example from the command line I get:
```
curl -s -w "\n" -X GET http://localhost:55588/
(node:832) nodeUnhandledPromiseRejectionWarning: TypeError: doc.addParagraph is not a function
    at app.get (/private/tmp/docxbug/docx-demo1-3.0.0/lib/docx-demo1.js:13:9)
    at Layer.handle [as handle_request] (/private/tmp/docxbug/node_modules/express/lib/router/layer.js:95:5)
    at next (/private/tmp/docxbug/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/private/tmp/docxbug/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/private/tmp/docxbug/node_modules/express/lib/router/layer.js:95:5)
    at /private/tmp/docxbug/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/private/tmp/docxbug/node_modules/express/lib/router/index.js:335:12)
    at next (/private/tmp/docxbug/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/private/tmp/docxbug/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/private/tmp/docxbug/node_modules/express/lib/router/layer.js:95:5)
(node:832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The bug does not appear to be in 5.0.0-rc4.

**Comment by dolanmiu** [comment]
Thanks for raising this, will fix.

It's because the API has changed from rc4 to rc5, it is now like so:

https://github.com/dolanmiu/docx/blob/master/demo/1-basic.ts

**Comment by gustavotogni** [comment]
Hi there,

I've been having lots of trouble with the API changes.
Any way to avoid rewriting most of my code?

Even the documentation I believe is not up to date in all places, like https://docx.js.org/#/usage/headers-and-footers.

**Comment by dolanmiu** [comment]
Check out the demo folder, those examples all work in the latest rc5

You can stay on `rc4` until you are ready to upgrade

If you email me personally, I am glad to help you with the re-write until theres better documentation

**Comment by dil-wainstead** [comment]
@dolanmiu thank you! I am having issues again with demo3 and lists; I'll open a new bug. Closing this one.
