### ISSUE TITLE
TableRow and TableRowProperties issues on upgrade v4.3.0 to v4.7.1

### ISSUE THREAD

**Issue by sdele** [dolanmiu/docx#622]
Hello,

To get a feature on floating image we have to upgrade our version of docx. 
We use NestJS for our backend.
Since I have upgrade the version to 4.7.1 I met some issues : 

1. First the import are no longer correct

```
/node_modules/docx/build/index"' has no exported member 'TableRow'.

import { Document, Paragraph, PageOrientation, TableCell, TableRow, Table, VMergeType,
  TableRowProperties, VerticalAlign, WidthType } from 'docx';
```
I tried to fix the import this way  :  

`import {TableRow, TableRowProperties} from "docx/build/file/table/table-row";`

it is really correct to use file inside build ?

2. When I fix import there is still an issue 

```
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
Error: Cannot find module 'docx/build/file/table/table-row'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```
@dolanmiu  can you help me on this ?

Thank you

**Comment by dolanmiu** [comment]
> import {TableRow, TableRowProperties} from "docx/build/file/table/table-row";

> it is really correct to use file inside build ?

No this is not the correct way, you shouldn't be importing from `docx/build`

V4 not really supported anymore :( sorry about this
