### ISSUE TITLE
SyntaxError: The requested module 'docx' does not provide an export named 'Packer'

### ISSUE THREAD

**Issue by DVGY** [dolanmiu/docx#681]
I am using node and I have added `type:module` in package.json and I am using this command to run `node --experimental-modules  index.js`

my node version is `v12.13.1`

I am getting this error, I have copied the code from `demo ` folder 

![image](https://user-images.githubusercontent.com/46158826/98458296-1892c080-21b5-11eb-8a54-5fa82902b68d.png)

My code is below 

I also get File is not constructor error if I use `import File from "docx";
import Packer from "docx";
 import Paragraph from "docx";
 import StyleLevel from "docx";
 import TableOfContents from "docx";`

this.

```ts
import * as fs from "fs";
import {
  // File,
  HeadingLevel,
  // Packer,
  Paragraph,
  StyleLevel,
  TableOfContents,
} from "docx";
import File from "docx";
import Packer from "docx";
// import Paragraph from "docx";
// import StyleLevel from "docx";
// import TableOfContents from "docx";

const doc = new File({
  styles: {
    paragraphStyles: [
      {
        id: "MySpectacularStyle",
        name: "My Spectacular Style",
        basedOn: "Heading1",
        next: "Heading1",
        quickFormat: true,
        run: {
          italics: true,
          color: "990000",
        },
      },
    ],
  },
});

// WordprocessingML docs for TableOfContents can be found here:
// http://officeopenxml.com/WPtableOfContents.php

// Let's define the properties for generate a TOC for heading 1-5 and MySpectacularStyle,
// making the entries be hyperlinks for the paragraph

doc.addSection({
  children: [
    new TableOfContents("Summary", {
      hyperlink: true,
      headingStyleRange: "1-5",
      stylesWithLevels: [new StyleLevel("MySpectacularStyle", 1)],
    }),
    new Paragraph({
      text: "Header #1",
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
    }),
    new Paragraph("I'm a little text very nicely written.'"),
    new Paragraph({
      text: "Header #2",
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
    }),
    new Paragraph("I'm a other text very nicely written.'"),
    new Paragraph({
      text: "Header #2.1",
      heading: HeadingLevel.HEADING_2,
    }),
    new Paragraph("I'm a another text very nicely written.'"),
    new Paragraph({
      text: "My Spectacular Style #1",
      style: "MySpectacularStyle",
      pageBreakBefore: true,
    }),
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("My Document.docx", buffer);
});
```

**Comment by dolanmiu** [comment]
try `import { Paragraph } from 'docx'`

Look at the examples in this folder here:

https://github.com/dolanmiu/docx/tree/master/demo

**Comment by DVGY** [comment]
> try `import { Paragraph } from 'docx'`
> 
> Look at the examples in this folder here:
> 
> https://github.com/dolanmiu/docx/tree/master/demo

Yes I tried copied the code from demo folder [](https://github.com/dolanmiu/docx/tree/master/demo) but it is not working as of now my code looks like this.

Recived a new error 

```
 File,
  ^^^^
SyntaxError: The requested module 'docx' does not provide an export named 'File'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:91:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:106:20)
    at async Loader.import (internal/modules/esm/loader.js:132:24)
PS C:\Users\Gaurav Yadav\Downloads\docx-demo2-5.0.0\demop> 
```
On console.logging File it give me this 
```
{
  Document: [Function: File],
  AlignmentType: {
    START: 'start',
    END: 'end',
    CENTER: 'center',
    BOTH: 'both',
    JUSTIFIED: 'both',
    DISTRIBUTE: 'distribute',
    LEFT: 'left',
    RIGHT: 'right'
  },
....
....
```

Code
```
import * as fs from "fs";

import File from "docx";
import Packer from "docx";
import Paragraph from "docx";
import StyleLevel from "docx";
import TableOfContents from "docx";
import HeadingLevel from "docx";

const doc = new File({
  styles: {
    paragraphStyles: [
      {
        id: "MySpectacularStyle",
        name: "My Spectacular Style",
        basedOn: "Heading1",
        next: "Heading1",
        quickFormat: true,
        run: {
          italics: true,
          color: "990000",
        },
      },
    ],
  },
});

// WordprocessingML docs for TableOfContents can be found here:
// http://officeopenxml.com/WPtableOfContents.php

// Let's define the properties for generate a TOC for heading 1-5 and MySpectacularStyle,
// making the entries be hyperlinks for the paragraph

doc.addSection({
  children: [
    new TableOfContents("Summary", {
      hyperlink: true,
      headingStyleRange: "1-5",
      stylesWithLevels: [new StyleLevel("MySpectacularStyle", 1)],
    }),
    new Paragraph({
      text: "Header #1",
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
    }),
    new Paragraph("I'm a little text very nicely written.'"),
    new Paragraph({
      text: "Header #2",
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
    }),
    new Paragraph("I'm a other text very nicely written.'"),
    new Paragraph({
      text: "Header #2.1",
      heading: HeadingLevel.HEADING_2,
    }),
    new Paragraph("I'm a another text very nicely written.'"),
    new Paragraph({
      text: "My Spectacular Style #1",
      style: "MySpectacularStyle",
      pageBreakBefore: true,
    }),
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("My Document.docx", buffer);
})
```;

**Comment by dolanmiu** [comment]
Its `Document`, not `File`

Try `Document`
